CREATE TABLE IF NOT EXISTS notes (
	id INTEGER PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	title VARCHAR(100) NOT NULL,
	body TEXT,
    last_edited TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
